import os
from dotenv import load_dotenv
from cs50 import SQL

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
is_postgres = False

if DATABASE_URL:
    is_postgres = True
    if DATABASE_URL.startswith("postgres://"):
        DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
    if DATABASE_URL.startswith("postgresql://"):
        DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)
    db = SQL(DATABASE_URL)
else:
    db = SQL("sqlite:///database.db")

try:
    if is_postgres:
        db.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL,
          type TEXT,
          message TEXT,
          reference_id TEXT,
          visto BOOLEAN DEFAULT FALSE,
          created_at TEXT DEFAULT (now()::text),
          CONSTRAINT fk_notifications_user
            FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
        );
        """)
    else:
        db.execute("""
        CREATE TABLE IF NOT EXISTS notifications (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          user_id INTEGER NOT NULL,
          type TEXT,
          message TEXT,
          reference_id TEXT,
          visto BOOLEAN DEFAULT FALSE,
          created_at TEXT DEFAULT (datetime('now','localtime')),
          CONSTRAINT fk_notifications_user
            FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
        );
        """)

    db.execute("CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);")

    print("Success: Tabela notifications criada com sucesso.")
except Exception as e:
    print(f"Erro: {e}")


