-- schema_postgres.sql

-- 1) tabelas "sobrando" do sqlite (opcional manter)
CREATE TABLE IF NOT EXISTS usuarios_backup_broken (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT,
  type TEXT NOT NULL DEFAULT 'funcionario'
);

-- 2) usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  senha_hash TEXT NOT NULL,
  email TEXT UNIQUE,
  type TEXT,
  created_at TEXT DEFAULT (now()::text),
  updated_at TEXT DEFAULT (now()::text),

  email_verified BOOLEAN DEFAULT FALSE,
  email_verified_at TEXT,
  email_verification_code_hash TEXT,
  email_verification_expires_at TEXT,
  email_verification_sent_at TEXT,
  email_verification_attempts INTEGER DEFAULT 0
);

-- 3) jobs
CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  payment_type TEXT,
  rate DOUBLE PRECISION,
  location TEXT,
  area TEXT,
  address TEXT,
  work_hours TEXT,
  posted_by TEXT,
  posted_at TEXT,
  period TEXT,
  duration TEXT,
  is_urgent BOOLEAN,
  professional_rating DOUBLE PRECISION,
  professional_reviews INTEGER,
  completed_jobs INTEGER,
  likes INTEGER,
  comments INTEGER,
  views INTEGER,
  company_only BOOLEAN,
  includes_food BOOLEAN,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  company_info_json TEXT,
  created_at TEXT DEFAULT (now()::text),

  -- no SQLite estava TEXT, mas faz sentido ser INTEGER (id do usuarios)
  posted_by_user_id INTEGER,
  cep TEXT,
  start_date TEXT,
  start_time TEXT,

  CONSTRAINT fk_jobs_posted_by_user
    FOREIGN KEY (posted_by_user_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- 4) resumes
CREATE TABLE IF NOT EXISTS resumes (
  id TEXT PRIMARY KEY,

  -- no SQLite estava TEXT, mas faz sentido ser INTEGER (id do usuarios)
  user_id INTEGER,

  personal_info_json TEXT,
  professional_info_json TEXT,
  work_experience_json TEXT,
  education_json TEXT,
  skills_json TEXT,
  bio TEXT,
  availability_json TEXT,
  created_at TEXT,
  updated_at TEXT,
  is_visible BOOLEAN,

  CONSTRAINT fk_resumes_user
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 5) user_profiles
CREATE TABLE IF NOT EXISTS user_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  user_id INTEGER NOT NULL UNIQUE,

  cnpj TEXT,
  company_name TEXT,
  company_email TEXT,
  business_type TEXT,
  company_description TEXT,

  full_name TEXT,
  cpf TEXT,
  phone TEXT,

  address TEXT,
  number INTEGER,
  complement TEXT,
  neighborhood TEXT,
  city TEXT,
  state TEXT,

  created_at TEXT NOT NULL DEFAULT (now()::text),
  updated_at TEXT,

  worker_category TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  cep TEXT,
  birth_date TEXT,
  imagem_profile TEXT,

  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 6) job_applications
CREATE TABLE IF NOT EXISTS job_applications (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,

  -- no SQLite estava TEXT mas referenciava usuarios(id) (INTEGER) -> tem que ser INTEGER no Postgres
  candidate_id INTEGER NOT NULL,

  status TEXT DEFAULT 'pending',
  created_at TEXT DEFAULT (now()::text),
  resume_id TEXT,

  CONSTRAINT fk_job_app_job
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,

  CONSTRAINT fk_job_app_candidate
    FOREIGN KEY (candidate_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Unique (equivalente ao seu unique index)
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_app_unique
  ON job_applications(job_id, candidate_id);

-- Índices
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_cnpj ON user_profiles(cnpj);
CREATE INDEX IF NOT EXISTS idx_user_profiles_cpf ON user_profiles(cpf);

CREATE INDEX IF NOT EXISTS idx_jobs_posted_by_user_id ON jobs(posted_by_user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_lat_lng ON jobs(lat, lng);
CREATE INDEX IF NOT EXISTS idx_profiles_lat_lng ON user_profiles(lat, lng);
