-- schema_postgres.sql

-- 1) legacy table kept from sqlite migration (optional)
CREATE TABLE IF NOT EXISTS usuarios_backup_broken (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT,
  type TEXT NOT NULL DEFAULT 'funcionario'
);

-- 2) usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  senha_hash TEXT NOT NULL,
  email TEXT UNIQUE,
  type TEXT,
  created_at TEXT DEFAULT (now()::text),
  updated_at TEXT DEFAULT (now()::text),

  email_verified BOOLEAN DEFAULT FALSE,
  email_verified_at TEXT,
  email_verification_code_hash TEXT,
  email_verification_expires_at TEXT,
  email_verification_sent_at TEXT,
  email_verification_attempts INTEGER DEFAULT 0,

  password_reset_token_hash TEXT,
  password_reset_expires_at TIMESTAMPTZ,
  password_reset_requested_at TIMESTAMPTZ,
  password_reset_used_at TIMESTAMPTZ,
  password_changed_at TIMESTAMPTZ
);

-- 3) jobs
CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  payment_type TEXT,
  rate DOUBLE PRECISION,
  location TEXT,
  area TEXT,
  address TEXT,
  work_hours TEXT,
  posted_by TEXT,
  posted_at TEXT,
  period TEXT,
  duration TEXT,
  is_urgent BOOLEAN,
  professional_rating DOUBLE PRECISION,
  professional_reviews INTEGER,
  completed_jobs INTEGER,
  likes INTEGER,
  comments INTEGER,
  views INTEGER,
  company_only BOOLEAN,
  includes_food BOOLEAN,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  company_info_json TEXT,
  created_at TEXT DEFAULT (now()::text),

  posted_by_user_id INTEGER,
  cep TEXT,
  status TEXT DEFAULT 'ativa',
  start_date TEXT,
  start_time TEXT,

  CONSTRAINT fk_jobs_posted_by_user
    FOREIGN KEY (posted_by_user_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- 4) resumes
CREATE TABLE IF NOT EXISTS resumes (
  id TEXT PRIMARY KEY,
  user_id INTEGER,
  personal_info_json TEXT,
  professional_info_json TEXT,
  work_experience_json TEXT,
  education_json TEXT,
  skills_json TEXT,
  bio TEXT,
  availability_json TEXT,
  created_at TEXT,
  updated_at TEXT,
  is_visible BOOLEAN,

  CONSTRAINT fk_resumes_user
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 5) user_profiles
CREATE TABLE IF NOT EXISTS user_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE,

  cnpj TEXT,
  company_name TEXT,
  company_email TEXT,
  business_type TEXT,
  company_description TEXT,

  full_name TEXT,
  cpf TEXT,
  phone TEXT,

  address TEXT,
  number INTEGER,
  complement TEXT,
  neighborhood TEXT,
  city TEXT,
  state TEXT,

  created_at TEXT NOT NULL DEFAULT (now()::text),
  updated_at TEXT,

  worker_category TEXT[],
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  cep TEXT,
  birth_date TEXT,
  imagem_profile TEXT,
  image_job TEXT[],
  rating DOUBLE PRECISION NOT NULL DEFAULT 0,
  reviews_count INTEGER NOT NULL DEFAULT 0,

  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 6) job_applications
CREATE TABLE IF NOT EXISTS job_applications (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL,
  candidate_id INTEGER NOT NULL,
  status TEXT DEFAULT 'pendente',
  created_at TEXT DEFAULT (now()::text),
  resume_id TEXT,

  CONSTRAINT fk_job_app_job
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,

  CONSTRAINT fk_job_app_candidate
    FOREIGN KEY (candidate_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- 7) notifications
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  type TEXT,
  message TEXT,
  reference_id TEXT,
  visto BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT (now()::text),

  CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_job_app_unique
  ON job_applications(job_id, candidate_id);

CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_cnpj ON user_profiles(cnpj);
CREATE INDEX IF NOT EXISTS idx_user_profiles_cpf ON user_profiles(cpf);

CREATE INDEX IF NOT EXISTS idx_jobs_posted_by_user_id ON jobs(posted_by_user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_lat_lng ON jobs(lat, lng);
CREATE INDEX IF NOT EXISTS idx_profiles_lat_lng ON user_profiles(lat, lng);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);

-- 8) user_evaluations
CREATE TABLE IF NOT EXISTS user_evaluations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluator_id INTEGER NOT NULL,
  evaluated_id INTEGER NOT NULL,
  job_id TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_evaluations_evaluator
    FOREIGN KEY (evaluator_id) REFERENCES usuarios(id) ON DELETE CASCADE,

  CONSTRAINT fk_evaluations_evaluated
    FOREIGN KEY (evaluated_id) REFERENCES usuarios(id) ON DELETE CASCADE,

  CONSTRAINT fk_evaluations_job
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_evaluations_evaluated_id ON user_evaluations(evaluated_id);
CREATE INDEX IF NOT EXISTS idx_user_evaluations_evaluator_id ON user_evaluations(evaluator_id);
CREATE INDEX IF NOT EXISTS idx_user_evaluations_job_id ON user_evaluations(job_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_evaluations_unique_review
  ON user_evaluations(evaluator_id, evaluated_id, job_id);
